### ISSUE TITLE
Research the codebase to identify where and how the separate CLI actions are defined and ran

### ISSUE THREAD

**Issue by StoyanDrumev** [LimeChain/cargo-stylus#1]

**Comment by reo101** [comment]
After reading and experimenting with the codebase, these are my findings (regarding the addition of a new `command`):

- The existing commands are defined [here](https://github.com/LimeChain/cargo-stylus/blob/a2ac0dd2bbc5ee4c731dd902d1d105aa192d603d/src/main.rs#L53) with most of them having a substructure holding their options
- What we need to define is a subcommand, i.e. a field in the enum that also has a substruct, but instead of `derive(Args)`, have a `derive(Command)`, because it will have its own subcommands (like `stylus script add`)
- Handling the command would happen [here](https://github.com/LimeChain/cargo-stylus/blob/a2ac0dd2bbc5ee4c731dd902d1d105aa192d603d/src/main.rs#L230) and preferably (follng the style of the other commands) call the actual implementation from a separate module (for instance `scripts`)

I've already started doing the implementation, will follow up in a commit/PR soon
